var SIZE_SMALL_NAME = 'mini burger';
var SIZE_SMALL_PRICE = 50;
var SIZE_SMALL_CALORIES = 20;

var SIZE_LARGE_NAME = 'big burger';
var SIZE_LARGE_PRICE = 100;
var SIZE_LARGE_CALORIES = 40;

var STUFFING_CHEESE_NAME = 'cheese burger';
var STUFFING_CHEESE_PRICE = 10;
var STUFFING_CHEESE_CALORIES = 20;

var STUFFING_SALAD_NAME = 'salad burger';
var STUFFING_SALAD_PRICE = 20;
var STUFFING_SALAD_CALORIES = 5;

var STUFFING_POTATO_NAME = 'potato burger';
var STUFFING_POTATO_PRICE = 15;
var STUFFING_POTATO_CALORIES = 10;

var DRINK_COLA_NAME = 'cola';
var DRINK_COLA_PRICE = 50;
var DRINK_COLA_CALORIES = 40;

var DRINK_COFFEE_NAME = 'coffee';
var DRINK_COFFEE_PRICE = 80;
var DRINK_COFFEE_CALORIES = 20;

var SALAD_CAESAR_NAME = 'caesar';
var SALAD_CAESAR_PRICE = 100;
var SALAD_CAESAR_CALORIES = 20;

var SALAD_OLIVIE_NAME = 'olivie';
var SALAD_OLIVIE_PRICE = 50;
var SALAD_OLIVIE_CALORIES = 80;

module.exports = {
    SIZE_SMALL_NAME: SIZE_SMALL_NAME,
    SIZE_SMALL_PRICE: SIZE_SMALL_PRICE,
    SIZE_SMALL_CALORIES: SIZE_SMALL_CALORIES,
    SIZE_LARGE_NAME: SIZE_LARGE_NAME,
    SIZE_LARGE_PRICE: SIZE_LARGE_PRICE,
    SIZE_LARGE_CALORIES: SIZE_LARGE_CALORIES,
    STUFFING_CHEESE_NAME: STUFFING_CHEESE_NAME,
    STUFFING_CHEESE_PRICE: STUFFING_CHEESE_PRICE,
    STUFFING_CHEESE_CALORIES: STUFFING_CHEESE_CALORIES,
    STUFFING_SALAD_NAME: STUFFING_SALAD_NAME,
    STUFFING_SALAD_PRICE: STUFFING_SALAD_PRICE,
    STUFFING_SALAD_CALORIES: STUFFING_SALAD_CALORIES,
    STUFFING_POTATO_NAME: STUFFING_POTATO_NAME,
    STUFFING_POTATO_PRICE: STUFFING_POTATO_PRICE,
    STUFFING_POTATO_CALORIES: STUFFING_POTATO_CALORIES,
    DRINK_COLA_NAME: DRINK_COLA_NAME,
    DRINK_COLA_PRICE: DRINK_COLA_PRICE,
    DRINK_COLA_CALORIES: DRINK_COLA_CALORIES,
    DRINK_COFFEE_NAME: DRINK_COFFEE_NAME,
    DRINK_COFFEE_PRICE: DRINK_COFFEE_PRICE,
    DRINK_COFFEE_CALORIES: DRINK_COFFEE_CALORIES,
    SALAD_CAESAR_NAME: SALAD_CAESAR_NAME,
    SALAD_CAESAR_PRICE: SALAD_CAESAR_PRICE,
    SALAD_CAESAR_CALORIES: SALAD_CAESAR_CALORIES,
    SALAD_OLIVIE_NAME: SALAD_OLIVIE_NAME,
    SALAD_OLIVIE_PRICE: SALAD_OLIVIE_PRICE,
    SALAD_OLIVIE_CALORIES: SALAD_OLIVIE_CALORIES

}